AWSTemplateFormatVersion: "2010-09-09"
Description: Save to Ink - API Backend resources

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project (used for resource naming)

  SourceBucketName:
    Type: String
    Description: Name of the S3 bucket containing the Lambda source code

  SourceBucketKey:
    Type: String
    Description: S3 key for the Lambda source zip file

  MailjetAPIKey:
    Type: String
    NoEcho: true
    Description: Mailjet API key

  MailjetAPISecret:
    Type: String
    NoEcho: true
    Description: Mailjet API secret

  APIKeySecret:
    Type: String
    NoEcho: true
    Description: Secret API key for authentication

  DestEmail:
    Type: String
    Description: Kindle email address

  SenderEmail:
    Type: String
    Description: Verified sender email address

  SendEnabled:
    Type: String
    Description: Enable email sending
    Default: "false"

  Auth0Domain:
    Type: String
    Description: Auth0 domain
    Default: ""

  Auth0Audience:
    Type: String
    Description: Auth0 audience
    Default: ""

  AuthBackend:
    Type: String
    Description: Auth backend
    Default: ""

  Debug:
    Type: String
    Description: Debug flag
    Default: "false"

  DomainName:
    Type: String
    Description: Custom domain name for the API (e.g. api.saveto.ink)
    Default: ""

  CertificateArn:
    Type: String
    Description: ACM certificate ARN for the custom domain (must be in us-east-1)
    Default: ""

  GitHubRepository:
    Type: String
    Description: "GitHub repository for OIDC authentication (format: owner/repo)"
    Default: "savetoink/savetoink"

Conditions:
  UseCustomDomain: !Not [!Equals [!Ref DomainName, ""]]

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-lambda-exec"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-api"
      Description: !Sub "${ProjectName} API - Article conversion and delivery service"
      Runtime: provided.al2023
      Handler: bootstrap
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref SourceBucketName
        S3Key: !Ref SourceBucketKey
      Timeout: 540
      MemorySize: 256
      Environment:
        Variables:
          SAVETOINK_API_KEY: !Ref APIKeySecret
          SAVETOINK_AUTH0_AUDIENCE: !Ref Auth0Audience
          SAVETOINK_AUTH0_DOMAIN: !Ref Auth0Domain
          SAVETOINK_AUTH_BACKEND: !Ref AuthBackend
          SAVETOINK_DEBUG: !Ref Debug
          SAVETOINK_DEST_EMAIL: !Ref DestEmail
          SAVETOINK_DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
          SAVETOINK_MAILJET_API_KEY: !Ref MailjetAPIKey
          SAVETOINK_MAILJET_API_SECRET: !Ref MailjetAPISecret
          SAVETOINK_SENDER_EMAIL: !Ref SenderEmail
          SAVETOINK_SEND_ENABLED: !Ref SendEnabled
      TracingConfig:
        Mode: PassThrough

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunction}"
      RetentionInDays: 30

  LambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      InvokeMode: BUFFERED
      TargetFunctionArn: !GetAtt LambdaFunction.Arn

  LambdaFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

  LambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: "*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: UseCustomDomain
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: /
        HttpVersion: http2and3
        PriceClass: PriceClass_100
        Origins:
          - Id: LambdaOrigin
            DomainName:
              !Select [
                0,
                !Split [
                  "/",
                  !Select [
                    1,
                    !Split ["://", !GetAtt LambdaFunctionUrl.FunctionUrl],
                  ],
                ],
              ]
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: LambdaOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          Compress: true
          ForwardedValues:
            Headers:
              - Authorization
              - User-Agent
            QueryString: true
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        CacheBehaviors:
          - PathPattern: /v1/*
            TargetOriginId: LambdaOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            Compress: true
            ForwardedValues:
              Headers:
                - Authorization
                - User-Agent
              QueryString: true
              Cookies:
                Forward: none
            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases:
          - !Ref DomainName

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-articles"
      AttributeDefinitions:
        - AttributeName: account
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: account
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  DynamoDBTableAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${ProjectName}-dynamodb-access"
      Roles:
        - !Ref LambdaExecutionRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Resource: !GetAtt DynamoDBTable.Arn

  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-github-actions"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubRepository}:ref:refs/heads/*"

  GitHubActionsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${ProjectName}-github-actions-deploy"
      Roles:
        - !Ref GitHubActionsRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub "arn:aws:s3:::${SourceBucketName}/*"
          - Effect: Allow
            Action:
              - lambda:UpdateFunctionCode
            Resource: !Sub "arn:aws:lambda:*:*:function:${ProjectName}-api"

Outputs:
  FunctionName:
    Description: Name of the Lambda function
    Value: !Ref LambdaFunction

  FunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn

  FunctionUrl:
    Description: Function URL endpoint
    Value: !GetAtt LambdaFunctionUrl.FunctionUrl
    Export:
      Name: !Sub "${ProjectName}-function-url"

  DynamoDBTableName:
    Description: Name of the DynamoDB table for storing articles
    Value: !Ref DynamoDBTable
    Export:
      Name: !Sub "${ProjectName}-dynamodb-table-name"

  DynamoDBTableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt DynamoDBTable.Arn
    Export:
      Name: !Sub "${ProjectName}-dynamodb-table-arn"

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution
    Condition: UseCustomDomain

  CloudFrontDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Condition: UseCustomDomain

  CustomDomainUrl:
    Description: Custom domain URL for the API
    Value: !Sub "https://${DomainName}"
    Condition: UseCustomDomain

  LogGroupName:
    Description: CloudWatch log group name for Lambda
    Value: !Ref LambdaLogGroup

  GitHubActionsRoleArn:
    Description: ARN of the GitHub Actions IAM role for OIDC authentication
    Value: !GetAtt GitHubActionsRole.Arn

  GitHubOIDCProviderArn:
    Description: ARN of the GitHub OIDC provider
    Value: !GetAtt GitHubOIDCProvider.Arn
