AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket for Lambda function source code storage

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket for Lambda source code

Resources:
  LambdaSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LambdaSourceBucket
      PolicyDocument:
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${LambdaSourceBucket.Arn}"
              - !Sub "${LambdaSourceBucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt LambdaSourceBucket.Arn
